# coding = utf-8
#No.2 数值小于4000000的斐波那契数列里偶数的总和
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
def compute(i):
    L1=1
    L2=2
    sum=0
    while L1<i and L2<i:
        if L1%2==0:
            sum = sum+L1  #sum += L1
        if L2%2==0:
            sum =sum+L2  #sum += L2
        L1=L1+L2
        L2=L2+L1
    return sum
print(compute(4000000))
#这段代码好像写得有点复杂
